"use client"

import { useEffect, useState } from "react"
import Link from "next/link"
import { usePathname, useRouter } from "next/navigation"
import { ArrowRight, BarChart3, CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CircleUserRound, Fuel, Heart, Menu, Search, ShieldCheck, SlidersHorizontal, Sparkles, Star, X, Zap } from "lucide-react"

const cars = [
  { id: "aurora", brand: "BMW", model: "7 Series", trim: "740i M Sport", year: 2024, price: 14500000, fuel: "Petrol", type: "Sedan", transmission: "Automatic", power: "375 bhp", km: "8,420 km", img: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=85", color: "Mineral White" },
  { id: "velar", brand: "Land Rover", model: "Range Rover Velar", trim: "Dynamic HSE", year: 2023, price: 11200000, fuel: "Petrol", type: "SUV", transmission: "Automatic", power: "246 bhp", km: "12,180 km", img: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=1200&q=85", color: "Santorini Black" },
  { id: "phantom", brand: "Mercedes-Benz", model: "S-Class", trim: "S 450 4MATIC", year: 2024, price: 17800000, fuel: "Petrol", type: "Sedan", transmission: "Automatic", power: "362 bhp", km: "5,920 km", img: "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=1200&q=85", color: "Obsidian Black" },
  { id: "macan", brand: "Porsche", model: "Macan", trim: "GTS", year: 2023, price: 9800000, fuel: "Petrol", type: "SUV", transmission: "Automatic", power: "434 bhp", km: "14,600 km", img: "https://images.unsplash.com/photo-1611651338412-8403fa6e3599?auto=format&fit=crop&w=1200&q=85", color: "Carmine Red" },
  { id: "e-tron", brand: "Audi", model: "Q8 e-tron", trim: "55 Quattro", year: 2024, price: 11900000, fuel: "Electric", type: "SUV", transmission: "Automatic", power: "402 bhp", km: "3,250 km", img: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=1200&q=85", color: "Glacier White" },
  { id: "continental", brand: "Bentley", model: "Continental GT", trim: "V8 Mulliner", year: 2022, price: 24500000, fuel: "Petrol", type: "Coupe", transmission: "Automatic", power: "542 bhp", km: "7,840 km", img: "https://images.unsplash.com/photo-1584345604476-8ec5e12e42dd?auto=format&fit=crop&w=1200&q=85", color: "Verdant Green" },
]

const money = (n:number) => `₹${(n/10000000).toFixed(2)} Cr`
const detail = (id:string) => cars.find(c => c.id === id) || cars[0]

function Header({ saved, compare }:{saved:string[], compare:string[]}) {
  const path = usePathname(); const router = useRouter(); const [open,setOpen] = useState(false); const [query,setQuery] = useState("")
  return <header className="nav"><Link href="/" className="brand"><span className="brand-mark">R</span><span>RANCHO <b>MOTORS</b></span></Link><nav className={open?"mobile-open":""}><Link href="/cars">Explore</Link><Link href="/compare">Compare <i>{compare.length}</i></Link><Link href="/emi-calculator">EMI Calculator</Link><Link href="/test-drive">Test Drive</Link></nav><div className="nav-actions"><button className="icon-btn" aria-label="Search" onClick={()=>setOpen(!open)}><Search size={18}/></button><Link href="/saved" className="saved-link"><Heart size={17} fill={saved.length?"currentColor":"none"}/> Saved <i>{saved.length}</i></Link><CircleUserRound size={19} className="profile"/><Link href="/cars" className="nav-cta">Find Your Car <ArrowRight size={15}/></Link><button className="menu-btn" onClick={()=>setOpen(!open)} aria-label="Menu"><Menu/></button></div>{open && <div className="search-pop"><Search size={17}/><input autoFocus placeholder="Search brand or model..." value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')router.push(`/cars?q=${query}`)}}/><button onClick={()=>setOpen(false)}><X size={17}/></button></div>}</header>
}

function Footer(){return <footer><div><Link href="/" className="brand"><span className="brand-mark">R</span><span>RANCHO <b>MOTORS</b></span></Link><p>Luxury, backed by logic.</p></div><div className="footer-links"><Link href="/cars">Explore cars</Link><Link href="/compare">Compare</Link><Link href="/emi-calculator">EMI calculator</Link><Link href="/test-drive">Book a test drive</Link></div><small>© 2024 Rancho Motors. Built for better decisions.</small></footer>}

function CarCard({car,saved,onSave,compare,onCompare}:{car:any,saved:boolean,onSave:()=>void,compare:boolean,onCompare:()=>void}){return <article className="car-card"><div className="car-image"><img src={car.img} alt={`${car.brand} ${car.model}`}/><span className="tag">{car.year} · {car.type}</span><button className={saved?"heart active":"heart"} onClick={onSave} aria-label="Save vehicle"><Heart size={18} fill={saved?"currentColor":"none"}/></button></div><div className="car-info"><div className="car-kicker">{car.brand}</div><h3>{car.model}</h3><p className="trim">{car.trim}</p><div className="spec-line"><span>{car.fuel}</span><span>{car.transmission}</span><span>{car.power}</span></div><div className="car-bottom"><strong>{money(car.price)}</strong><span>starting price</span></div><div className="card-actions"><Link href={`/cars/${car.id}`}>View details <ArrowRight size={14}/></Link><button className={compare?"compare active":"compare"} onClick={onCompare}><BarChart3 size={15}/> {compare?"Added":"Compare"}</button></div></div></article>}

function Empty({title,body,href,label}:{title:string,body:string,href:string,label:string}){return <div className="empty"><Sparkles size={28}/><h2>{title}</h2><p>{body}</p><Link className="btn dark" href={href}>{label} <ArrowRight size={16}/></Link></div>}

function Home({saved,setSaved,compare,setCompare}:{saved:string[],setSaved:any,compare:string[],setCompare:any}){const router=useRouter(); const [brand,setBrand]=useState("All brands"); return <><section className="hero"><div className="hero-copy"><div className="eyebrow"><span/>RANCHO MOTORS · EST. 2024</div><h1>Luxury,<br/><em>backed by logic.</em></h1><p>Find the right luxury car through data, comparison, and transparent buying tools.</p><div className="hero-actions"><Link href="/cars" className="btn light">Explore cars <ArrowRight size={16}/></Link><Link href="/compare" className="text-btn">Compare vehicles <BarChart3 size={16}/></Link></div></div><div className="hero-image"><img src={cars[0].img} alt="BMW 7 Series in a dark studio"/><div className="hero-stat"><small>01 / 06</small><span>Curated for clarity</span></div></div><div className="scroll-note">SCROLL TO EXPLORE <ChevronDown size={15}/></div></section><main><section className="finder"><div><div className="eyebrow dark-eyebrow"><span/>THE RANCHO METHOD</div><h2>Find your next car.</h2><p>Start with what matters to you.</p></div><div className="finder-controls"><label>Brand<select value={brand} onChange={e=>setBrand(e.target.value)}><option>All brands</option>{[...new Set(cars.map(c=>c.brand))].map(b=><option key={b}>{b}</option>)}</select></label><label>Body type<select><option>Any body type</option><option>SUV</option><option>Sedan</option><option>Coupe</option></select></label><label>Budget<select><option>Any budget</option><option>Under ₹1 Cr</option><option>₹1–2 Cr</option><option>Above ₹2 Cr</option></select></label><button className="btn dark" onClick={()=>router.push(`/cars${brand!=="All brands"?`?brand=${encodeURIComponent(brand)}`:""}`)}>Search cars <Search size={16}/></button></div></section><section className="section"><div className="section-head"><div><div className="eyebrow dark-eyebrow"><span/>EDITOR&apos;S SELECTION</div><h2>Featured vehicles</h2><p>Curated luxury cars for buyers who know what they want.</p></div><Link href="/cars" className="text-btn dark-text">View all cars <ArrowRight size={16}/></Link></div><div className="car-grid">{cars.map(car=><CarCard key={car.id} car={car} saved={saved.includes(car.id)} onSave={()=>setSaved((s:string[])=>s.includes(car.id)?s.filter(x=>x!==car.id):[...s,car.id])} compare={compare.includes(car.id)} onCompare={()=>setCompare((s:string[])=>s.includes(car.id)?s.filter(x=>x!==car.id):s.length<3?[...s,car.id]:s)}/>)}</div></section><section className="logic-band"><div><div className="eyebrow"><span/>BUY WITH CONFIDENCE</div><h2>Looks are subjective.<br/><em>Numbers aren&apos;t.</em></h2></div><div className="logic-items"><div><ShieldCheck/><strong>Verified inventory</strong><p>Every car inspected and verified.</p></div><div><BarChart3/><strong>Compare with clarity</strong><p>Side-by-side data, no guesswork.</p></div><div><Zap/><strong>Tools that help</strong><p>EMI, valuations, and more.</p></div></div></section></main></>}

function CarsPage({saved,setSaved,compare,setCompare}:{saved:string[],setSaved:any,compare:string[],setCompare:any}){const [search,setSearch]=useState("");const [type,setType]=useState("All");const [sort,setSort]=useState("featured");const [filtersOpen,setFiltersOpen]=useState(false);useEffect(()=>{const params=new URLSearchParams(window.location.search);setSearch(params.get("q")||params.get("brand")||"")},[]);const filtered=cars.filter(c=>(!search||`${c.brand} ${c.model}`.toLowerCase().includes(search.toLowerCase()))&&(type==='All'||c.type===type)).sort((a,b)=>sort==='price-low'?a.price-b.price:sort==='price-high'?b.price-a.price:b.year-a.year);const toggleCompare=(id:string)=>setCompare((s:string[])=>s.includes(id)?s.filter(x=>x!==id):s.length<3?[...s,id]:s);return <main className="page"><div className="page-heading"><div><div className="eyebrow dark-eyebrow"><span/>THE COLLECTION</div><h1>Explore vehicles</h1><p>Six considered choices. One that feels right.</p></div><div className="result-count">{filtered.length} vehicles</div></div><div className="filterbar"><div className="input-wrap"><Search size={17}/><input aria-label="Search make or model" placeholder="Search make or model" value={search} onChange={e=>setSearch(e.target.value)}/></div><div className="pills">{['All','SUV','Sedan','Coupe'].map(x=><button key={x} className={type===x?'pill active':'pill'} onClick={()=>setType(x)}>{x}</button>)}</div><button className="filter-btn" onClick={()=>setFiltersOpen(v=>!v)} aria-expanded={filtersOpen}><SlidersHorizontal size={16}/> Filters</button>{filtersOpen&&<label className="sort-control">Sort by<select aria-label="Sort vehicles" value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label>}</div><div className="car-grid listing">{filtered.length?filtered.map(car=><CarCard key={car.id} car={car} saved={saved.includes(car.id)} onSave={()=>setSaved((s:string[])=>s.includes(car.id)?s.filter(x=>x!==car.id):[...s,car.id])} compare={compare.includes(car.id)} onCompare={()=>toggleCompare(car.id)}/>):<Empty title="No cars match that search" body="Try another make, model, or body type." href="/cars" label="Reset filters"/>}</div></main>}

function DetailPage({id,saved,setSaved,compare,setCompare}:{id:string,saved:string[],setSaved:any,compare:string[],setCompare:any}){const car=cars.find(item=>item.id===id);if(!car)return <main className="page"><Empty title="Vehicle not found" body="That vehicle is no longer in the collection." href="/cars" label="Explore cars"/></main>;return <main className="detail-page"><Link href="/cars" className="back"><ChevronLeft size={17}/> Back to collection</Link><div className="detail-grid"><div className="detail-photo"><img src={car.img} alt={`${car.brand} ${car.model}`}/><span className="photo-count">01 / 04</span></div><div className="detail-copy"><div className="eyebrow dark-eyebrow"><span/>{car.brand.toUpperCase()} · {car.year}</div><h1>{car.model}</h1><p className="detail-trim">{car.trim} · {car.color}</p><div className="detail-price"><strong>{money(car.price)}</strong><span>Indicative starting price</span></div><div className="detail-specs"><div><small>Power</small><b>{car.power}</b></div><div><small>Fuel</small><b>{car.fuel}</b></div><div><small>Odometer</small><b>{car.km}</b></div><div><small>Transmission</small><b>{car.transmission}</b></div></div><div className="detail-actions"><Link href="/test-drive" className="btn dark">Book a test drive <ArrowRight size={16}/></Link><button className="outline-btn" onClick={()=>setSaved((s:string[])=>s.includes(car.id)?s.filter(x=>x!==car.id):[...s,car.id])}><Heart size={17} fill={saved.includes(car.id)?"currentColor":"none"}/> {saved.includes(car.id)?"Saved":"Save car"}</button><button className="outline-btn" onClick={()=>setCompare((s:string[])=>s.includes(car.id)?s.filter(x=>x!==car.id):s.length<3?[...s,car.id]:s)}><BarChart3 size={17}/> Compare</button></div><p className="disclaimer"><ShieldCheck size={16}/> This vehicle has passed Rancho&apos;s 150-point inspection.</p></div></div><section className="detail-section"><div><div className="eyebrow dark-eyebrow"><span/>WHY THIS CAR</div><h2>Quiet confidence.</h2></div><p>Designed for those who value the details, the {car.model} balances effortless performance with an interior that makes every journey feel considered.</p></section></main>}

function ComparePage({compare,setCompare}:{compare:string[],setCompare:any}){const selected=compare.map(detail);return <main className="page"><div className="page-heading"><div><div className="eyebrow dark-eyebrow"><span/>DECIDE WITH DATA</div><h1>Compare vehicles</h1><p>Put the details side by side. The right answer gets clearer.</p></div></div>{selected.length<2?<Empty title="Your shortlist is waiting" body="Add at least two cars to compare their specs, price, and ownership details side by side." href="/cars" label="Explore cars"/>:<div className="compare-wrap"><div className="compare-head"><div className="compare-label">At a glance</div>{selected.map(c=><div key={c.id}><img src={c.img} alt=""/><button onClick={()=>setCompare((s:string[])=>s.filter(x=>x!==c.id))}><X size={14}/></button><b>{c.brand} {c.model}</b><strong>{money(c.price)}</strong></div>)}</div>{[['Year','year'],['Body type','type'],['Fuel type','fuel'],['Power','power'],['Transmission','transmission'],['Odometer','km']].map(([label,key])=><div className="compare-row" key={key}><span>{label}</span>{selected.map(c=><b key={c.id}>{c[key as keyof typeof c]}</b>)}</div>)}<div className="compare-cta"><span>Need help deciding?</span><Link href="/test-drive" className="btn dark">Experience them in person <ArrowRight size={16}/></Link></div></div>}</main>}

function EmiPage(){const [price,setPrice]=useState(12000000);const [down,setDown]=useState(3000000);const [rate,setRate]=useState(8.5);const [years,setYears]=useState(5);const principal=price-down;const monthly=principal*(rate/1200)*Math.pow(1+rate/1200,years*12)/(Math.pow(1+rate/1200,years*12)-1);return <main className="page emi-page"><div className="page-heading"><div><div className="eyebrow dark-eyebrow"><span/>PLAN WITH CLARITY</div><h1>EMI calculator</h1><p>Understand the monthly number before you fall for the car.</p></div></div><div className="emi-grid"><div className="calculator"><label>Car price <output>₹{(price/100000).toFixed(0)} L</output><input type="range" min="3000000" max="30000000" step="100000" value={price} onChange={e=>setPrice(+e.target.value)}/></label><label>Down payment <output>₹{(down/100000).toFixed(0)} L</output><input type="range" min="0" max={price*.8} step="100000" value={down} onChange={e=>setDown(+e.target.value)}/></label><label>Interest rate <output>{rate}%</output><input type="range" min="6" max="14" step=".1" value={rate} onChange={e=>setRate(+e.target.value)}/></label><label>Loan tenure <output>{years} years</output><input type="range" min="1" max="7" step="1" value={years} onChange={e=>setYears(+e.target.value)}/></label></div><div className="emi-result"><div className="donut"><div><small>Monthly EMI</small><strong>₹{Math.round(monthly).toLocaleString('en-IN')}</strong></div></div><div className="result-lines"><span>Loan amount <b>₹{(principal/100000).toFixed(1)} L</b></span><span>Total interest <b>₹{Math.round(monthly*years*12-principal).toLocaleString('en-IN')}</b></span><span>Total payable <b>₹{Math.round(monthly*years*12).toLocaleString('en-IN')}</b></span></div><Link href="/cars" className="btn dark">Find a car for this budget <ArrowRight size={16}/></Link><small className="note">Indicative calculation. Final terms depend on your lender.</small></div></div></main>}

function TestDrive(){const [done,setDone]=useState(false);const [name,setName]=useState("");const [email,setEmail]=useState("");const [date,setDate]=useState("");const [carId,setCarId]=useState(cars[0].id);const submit=()=>{if(!name.trim()||!/^\S+@\S+\.\S+$/.test(email)||!date)return;const booking={id:Date.now().toString(),name:name.trim(),email,carId,date,status:"CONFIRMED"};const existing=JSON.parse(localStorage.getItem('rancho-bookings')||'[]');localStorage.setItem('rancho-bookings',JSON.stringify([...existing,booking]));setDone(true)};return <main className="page narrow"><div className="page-heading"><div><div className="eyebrow dark-eyebrow"><span/>COME SEE FOR YOURSELF</div><h1>Book a test drive</h1><p>Good decisions deserve a proper drive.</p></div></div>{done?<div className="confirmation"><div className="confirm-icon"><Check/></div><div className="eyebrow dark-eyebrow"><span/>YOU&apos;RE ALL SET</div><h2>Your drive is booked.</h2><p>We&apos;ll be in touch shortly to confirm the details. Bring your curiosity — we&apos;ll bring the car.</p><Link href="/bookings" className="btn dark">View my bookings <ArrowRight size={16}/></Link></div>:<div className="booking-form"><label>Your name<input placeholder="Aarav Mehta" value={name} onChange={e=>setName(e.target.value)} required/></label><label>Email address<input type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Which car would you like to drive?<select value={carId} onChange={e=>setCarId(e.target.value)}>{cars.map(c=><option key={c.id} value={c.id}>{c.brand} {c.model}</option>)}</select></label><div className="form-row"><label>Preferred date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Preferred time<select><option>Morning, 10:00 AM</option><option>Afternoon, 2:00 PM</option><option>Evening, 5:00 PM</option></select></label></div><button className="btn dark" disabled={!name.trim()||!email||!date} onClick={submit}>Confirm test drive <ArrowRight size={16}/></button><p className="form-note">By continuing, you agree to receive a confirmation from Rancho Motors.</p></div>}</main>}

function SavedPage({saved,setSaved,compare,setCompare}:{saved:string[],setSaved:any,compare:string[],setCompare:any}){const list=cars.filter(c=>saved.includes(c.id));return <main className="page"><div className="page-heading"><div><div className="eyebrow dark-eyebrow"><span/>YOUR GARAGE</div><h1>Saved cars</h1><p>Your considered shortlist, all in one place.</p></div></div>{list.length?<div className="car-grid">{list.map(car=><CarCard key={car.id} car={car} saved onSave={()=>setSaved((s:string[])=>s.filter(x=>x!==car.id))} compare={compare.includes(car.id)} onCompare={()=>setCompare((s:string[])=>s.includes(car.id)?s.filter(x=>x!==car.id):s.length<3?[...s,car.id]:s)}/>)}</div>:<Empty title="Nothing saved yet" body="Tap the heart on any vehicle you want to come back to." href="/cars" label="Explore cars"/>}</main>}

function Bookings(){const [bookings,setBookings]=useState<any[]>([]);useEffect(()=>{try{setBookings(JSON.parse(localStorage.getItem('rancho-bookings')||'[]'))}catch{}},[]);const cancel=(id:string)=>{const next=bookings.filter(b=>b.id!==id);setBookings(next);localStorage.setItem('rancho-bookings',JSON.stringify(next))};return <main className="page"><div className="page-heading"><div><div className="eyebrow dark-eyebrow"><span/>YOUR JOURNEY</div><h1>Bookings</h1><p>Keep track of the cars you&apos;re getting to know.</p></div></div>{bookings.length?bookings.map(b=>{const car=detail(b.carId);return <div className="booking-card" key={b.id}><div className="booking-date"><small>DATE</small><strong>{new Date(b.date).getDate()}</strong><small>{new Date(b.date).toLocaleDateString('en-IN',{month:'short'}).toUpperCase()}</small></div><div><span className="status">{b.status}</span><h3>{car.brand} {car.model} · {car.trim}</h3><p><CalendarDays size={15}/> {new Date(b.date).toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</p><p><span className="pin">⌖</span> Rancho Motors, Bandra West</p></div><button className="outline-btn" onClick={()=>cancel(b.id)}>Cancel booking</button></div>}) : <Empty title="No bookings yet" body="Book a test drive when you find a car worth experiencing." href="/test-drive" label="Book a test drive"/>}</main>}

export default function Page(){const path=usePathname();const [saved,setSaved]=useState<string[]>([]);const [compare,setCompare]=useState<string[]>([]);const [hydrated,setHydrated]=useState(false);useEffect(()=>{try{const storedSaved=JSON.parse(localStorage.getItem('rancho-saved')||'[]');const storedCompare=JSON.parse(localStorage.getItem('rancho-compare')||'[]');setSaved(Array.isArray(storedSaved)?storedSaved.filter((id:string)=>cars.some(car=>car.id===id)):[]);setCompare(Array.isArray(storedCompare)?storedCompare.filter((id:string)=>cars.some(car=>car.id===id)).slice(0,3):[])}catch{}finally{setHydrated(true)}},[]);useEffect(()=>{if(hydrated)localStorage.setItem('rancho-saved',JSON.stringify(saved))},[saved,hydrated]);useEffect(()=>{if(hydrated)localStorage.setItem('rancho-compare',JSON.stringify(compare))},[compare,hydrated]);const content=path==="/"?<Home {...{saved,setSaved,compare,setCompare}}/>:path==="/cars"?<CarsPage {...{saved,setSaved,compare,setCompare}}/>:path.startsWith("/cars/")?<DetailPage id={path.split('/')[2]} {...{saved,setSaved,compare,setCompare}}/>:path==="/compare"?<ComparePage compare={compare} setCompare={setCompare}/>:path==="/emi-calculator"?<EmiPage/>:path==="/test-drive"?<TestDrive/>:path==="/saved"?<SavedPage {...{saved,setSaved,compare,setCompare}}/>:<Bookings/>;return <><Header saved={saved} compare={compare}/>{content}<Footer/></>}

export { cars }

